server:
  AppVersion: 1.0.0
  Port: :6001
  Mode: Development
  JwtSecretKey: secretkey
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: debug

licenseKey:
  FineCalculatorLicenseKey: HX783-K2L7V-CRJ4A-5PN1G