
// Publish speeding violation
POST http://127.0.0.1:6001/collectfine
Content-Type: application/json

{ 
  "vehicle_id": "RT-318-K", 
  "road_id": "A12", 
  "violation_in_kmh": 15,
  "timestamp": "2020-09-20T08:33:41.338+07:00" 
}